apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gac 
  janus-idp.io/tekton: gac
  backstage.io/kubernetes-id: gac
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gac
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  