apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gac-gitops
  description: This is GitOps manifest for gac   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: gac
    backstage.io/kubernetes-id: gac 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: northdepot/gac-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gac
