apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gac
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gac 
  name: gac
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gac 
